package com.lilly.cirrus.jenkinsdsl.sim

interface PipelineMock {
  def getEnv()
  def getScm()
  def stage(String name, Closure<?> body)
  def parallel(Map... maps)
  def sh(String command)
  def sh(Map args)
  def dir(String path, Closure<?> body)
  def echo(String text)
  def error(String text)
  def evaluate(String text)
  def stash(Map args)
  def unstash(String name)
  def checkout(def scm)
  def containerTemplate(Map args)
  def podTemplate(Map args, Closure<?> body)
  def node(String label, Closure<?> body)
  def container(String name, Closure<?> body)
  def withCredentials(List credentials, Closure<?> body)
  def usernamePassword(Map args)
  def usernameColonPassword(Map args)
  def certificate(Map args)
  def string(Map args)
  def file(Map args)

  def selector(String... list)
  def describe()
  def exists()
  def create(String... list)
  def create(List list)
  def secrets(String... list)
  def secrets(List list)
  def raw(String... list)
  def raw(List list)
  def delete(String... list)
  def delete(List list)
  def delete()
  def withCluster(Closure closure)
  def withCluster(String url, String token, Closure closure)
  def withProject(String name, Closure closure)
  def withCredentials(String credentials, Closure<?> body)
  def startBuild(String... list)
  def startBuild(List list)
  def rollout()
  def latest()

  def readJSON(Map args)
  def readYaml(Map args)
  def readTrusted(String path)
  def readFile(Map args)
  def readFile(String path)
  def writeFile(Map args)
  def fileExists(String path)
  def touch(String path)
  def load(String path)
  def zip(Map args)

  def libraryResource(String path)
  def archiveArtifacts(String path)
  def archiveArtifacts(Map args)
}
