
name: SNAPSHOT

on:
  push:
    branches: [ master, develop, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          command: monitor

      - name: Gradle Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build

      - name: Upload Build Artifacts
        if: github.ref == 'refs/heads/master'
        uses: eskatos/gradle-command-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          arguments: publish
  
