
name: RELEASE

on:
  release:
    types: [created]

jobs:
  perform-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF##*/})

#      - name: Publish Release Artifact
#        uses: eskatos/gradle-command-action@v1
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
#        with:
#          arguments: -Pversion=${RELEASE_VERSION} publish

      - name: Show the version
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: echo ${RELEASE_VERSION}
